Add sanctum token auth support
manchenkoff/nuxt-laravel-echo pull request #45
Opened 2024-10-30 08:41 UTC by allnightru

Add support for the token-based sanctum authentication.
Implementation inspired by nuxt-auth-sanctum module.
- Added config parameter: echo.authentication.mode, "cookie" or "token".
- Added support for external tokenStorage (implementation from nuxt-auth-sanctum module)
- Changed "onRequest" hook to send Bearer token if authentication.mode is "token".

2024-10-30 11:29 UTC, manchenkoff commented
Hey @allnightru, thanks for the contribution! I'll try to review this one today, in the meantime, pls check linter issues

2024-10-30 11:30 UTC, manchenkoff commented on src/runtime/types.ts
> +  tokenStorage?: TokenStorage
I think this is supposed to be used as app options interface and not ModuleOptions, you can check how it is defined in `nuxt-auth-sanctum` as well

2024-11-03 21:51 UTC, manchenkoff commented
Closes #44

2024-11-03 21:52 UTC, manchenkoff commented on src/runtime/plugin.client.ts
> +      // todo: move this to interceptors
interceptors are not really needed here unless we have more layers to apply, so I would suggest either removing todo comments or creating a new issue instead

2024-11-03 21:53 UTC, manchenkoff requested changes
minor changes and fixing linter issues are needed

2024-11-27 09:22 UTC, ivan-plotnikov commented
+1

2024-12-19 23:06 UTC, manchenkoff commented
UPD: needs to be tested

2024-12-21 11:18 UTC, manchenkoff approved these changes

2024-12-21 11:18 UTC, merged